export const TEST_ACTION = "TEST_ACTION";

export const UPDATE_SHIPPER_CONS_ADDRESS_INFO = "UPDATE_SHIPPER_CONS_ADDRESS_INFO";
export const UPDATE_SHIPPER_CONS_ADDRESS_MUL_INFO = "UPDATE_SHIPPER_CONS_ADDRESS_MUL_INFO";
export const UPDATE_SHIPPER_CONS_OTHER_INFO = "UPDATE_SHIPPER_CONS_OTHER_INFO";
export const UPDATE_SHIPPER_CONS_ADDRESS_BOOK_INFO = "UPDATE_SHIPPER_CONS_ADDRESS_BOOK_INFO";

export const UPDATE_REFERENCE_OBJ = "UPDATE_REFERENCE_OBJ";
export const UPDATE_REFERENCE_INFO = "UPDATE_REFERENCE_INFO";
export const UPDATE_REFERENCE_INFO_ADD_REFNUM = "UPDATE_REFERENCE_INFO_ADD_REFNUM";
export const UPDATE_REFERENCE_INFO_DEL_REFNUM = "UPDATE_REFERENCE_INFO_DEL_REFNUM";
export const UPDATE_REFERENCE_INFO_REFNUM = "UPDATE_REFERENCE_INFO_REFNUM";

export const UPDATE_SHIPMENT_DETAILS = "UPDATE_SHIPMENT_DETAILS";
export const UPDATE_SHIPMENT_DESCRIPTION = "UPDATE_SHIPMENT_DESCRIPTION";
export const UPDATE_SHIPMENT_DETAILS_FIELD = "UPDATE_SHIPMENT_DETAILS_FIELD";

export const UPDATE_MARSH_INSURANCE_INFO = "UPDATE_MARSH_INSURANCE_INFO";
export const UPDATE_PICK_UP_DETAILS_OBJ = "UPDATE_PICK_UP_DETAILS_OBJ";
export const UPDATE_PICK_UP_DETAILS_INFO = "UPDATE_PICK_UP_DETAILS_INFO";
export const UPDATE_BOL_TYPE_INFO = "UPDATE_BOL_TYPE_INFO";
export const UPDATE_SALES_PRICE_INFO = "UPDATE_SALES_PRICE_INFO";

export const UPDATE_ADDITIONAL_INFO = "UPDATE_ADDITIONAL_INFO";
export const UPDATE_HAZMAT = "UPDATE_HAZMAT";

export const UPDATE_ADDRESS_BOOK_DATA = "UPDATE_ADDRESS_BOOK_DATA";


export const UPDATE_IS_VALIDATION_TRIGGERED = "UPDATE_IS_VALIDATION_TRIGGERED";


export const UPDATE_IS_SECTION_VAL_TRIGGERED = "UPDATE_IS_SECTION_VAL_TRIGGERED";
export const UPDATE_VALID_SECTIONS = "UPDATE_VALID_SECTIONS";
export const UPDATE_HIGHLIGHTED_TILL = "UPDATE_HIGHLIGHTED_TILL";

export const UPDATE_SEL_SHIPPER_ID = "UPDATE_SEL_SHIPPER_ID";
export const UPDATE_SEL_CONSIGNEE_ID = "UPDATE_SEL_CONSIGNEE_ID";
export const UPDATE_IS_SHIPPER_CONS_INFO_CHNGD = "UPDATE_IS_SHIPPER_CONS_INFO_CHNGD";
export const UPDATE_SHOW_ADDRESS_CHNG_CONF = "UPDATE_SHOW_ADDRESS_CHNG_CONF";

export const UPDATE_ADDRESS_BOOK_ENTRY = "UPDATE_ADDRESS_BOOK_ENTRY";

export const CLEAR_BOL_DATA = "CLEAR_BOL_DATA";
export const UPD_ERR_OBJ = "UPD_ERR_OBJ";

export const UPD_BOL_OBJ = "UPD_BOL_OBJ";

export const UPDATE_PRINTQUOTE_OBJ = "UPDATE_PRINTQUOTE_OBJ";