export const OPEN_SHIPMENT_NOTES_MODAL = "OPEN_SHIPMENT_NOTES_MODAL";
export const CLOSE_SHIPMENT_NOTES_MODAL = "CLOSE_SHIPMENT_NOTES_MODAL";

export const OPEN_SHIPMENT_NOTES_ADD_NOTES_MODAL = "OPEN_SHIPMENT_NOTES_ADD_NOTES_MODAL";
export const CLOSE_SHIPMENT_NOTES_ADD_NOTES_MODAL = "CLOSE_SHIPMENT_NOTES_ADD_NOTES_MODAL";

export const OPEN_SHIPMENT_DETAILS_MODAL = "OPEN_SHIPMENT_DETAILS_MODAL";
export const CLOSE_SHIPMENT_DETAILS_MODAL = "CLOSE_SHIPMENT_DETAILS_MODAL";

export const OPEN_DISPATCH_MENU_DIALOG_MODAL = "OPEN_DISPATCH_MENU_DIALOG_MODAL";
export const CLOSE_DISPATCH_MENU_DIALOG_MODAL = "CLOSE_DISPATCH_MENU_DIALOG_MODAL";

export const OPEN_SCHEDULE_PICKUP_DIALOG_MODAL = "OPEN_SCHEDULE_PICKUP_DIALOG_MODAL";
export const CLOSE_SCHEDULE_PICKUP_DIALOG_MODAL = "CLOSE_SCHEDULE_PICKUP_DIALOG_MODAL";

export const OPEN_BOL_DETAIL_MODAL = "OPEN_BOL_DETAIL_MODAL";
export const CLOSE_BOL_DETAIL_MODAL = "CLOSE_BOL_DETAIL_MODAL";

export const OPEN_TRACKING_SHIPMENT_MODAL = "OPEN_TRACKING_SHIPMENT_MODAL";
export const CLOSE_TRACKING_SHIPMENT_MODAL = "CLOSE_TRACKING_SHIPMENT_MODAL";

export const OPEN_VOID_SHIPMENT_MODAL = "OPEN_VOID_SHIPMENT_MODAL";
export const CLOSE_VOID_SHIPMENT_MODAL = "CLOSE_VOID_SHIPMENT_MODAL";

export const TOGGLE_VIEW_COLUMN_SETTING = 'TOGGLE_VIEW_COLUMN_SETTING';
export const RESTORE_COLUMN_SETTING = 'RESTORE_COLUMN_SETTING';

export const CHANGE_COLUMN_ORDER_FREIGHT_HISTORY = 'CHANGE_COLUMN_ORDER_FREIGHT_HISTORY';