export const TOGGLE_VIEW_COLUMN_SETTING_SAVEDQUOTES = 'TOGGLE_VIEW_COLUMN_SETTING_SAVEDQUOTES';
export const RESTORE_COLUMN_SETTING_SAVEDQUOTES = 'RESTORE_COLUMN_SETTING_SAVEDQUOTES';

export const OPEN_DELETE_QUOTE_MODAL = 'OPEN_DELETE_QUOTE_MODAL';
export const CLOSE_DELETE_QUOTE_MODAL = 'CLOSE_DELETE_QUOTE_MODAL';

export const CHANGE_COLUMN_ORDER_SAVED_QUOTES = 'CHANGE_COLUMN_ORDER_SAVED_QUOTES';
