export type ShipmentResponse = {
    id: number | null,
    uuid: string | null,
    success: boolean,
    errors: null,
    collection: boolean,
    elementCount: number,
    pageSize: number,
    pageNumber: number,
    pageCount: number,
    sortField: string,
    sortOrder: string,
    data: ShipmentTypes[],
    dataType: string,
    message: string | null
}

export type ShipmentTypes = {
    providerId:  number,
    shipmentId:  number,
    displayStatus:  string,
    providerStatusCode:  number,
    statusEnumName:  string,
    hotShipment:  boolean,
    note: string | null,
    serviceType:  string,
    shipDate:  string,
    senderName:  string,
    senderCompanyName:  string,
    senderAddress1: string,
    senderAddress2: string | null,
    senderAddress3: string | null,
    senderCity: string,
    senderPostalCode: string,
    senderStateCode: string,
    senderCountryCode: string,
    receiverName: string | null,
    receiverCompanyName: string,
    receiverAddress1: string,
    receiverAddress2: string | null,
    receiverAddress3: string | null,
    receiverCity: string ,
    receiverPostalCode: string,
    receiverStateCode:string,
    receiverCountryCode:string,
    issuedBoLNumber: string,
    customerBoLNumber:  string,
    unitType: string | null,
    numberOfItems: number,
    issuedProNumber: string,
    customerProNumber: string,
    pickupDateTime: string | null,
    carrierName: string,
    carrierPhone: string | null,
    carrierEmail: string | null,
    carrierWebAddress: string | null,
    tariffDescription: string,
    insuredAmount: number,
    displayInsuredAmount: number,
    deliveryDate: string | null,
    totalWeight: number,
    quotedAmount: number,
    displayQuotedAmount: string,
    tag:  null
}


